
const images = {
    logoImg: require('../assets/icon/logo.png'),
    bgImg: require('../assets/icon/Bg_yel.png'),
    nextImg: require('../assets/icon/next.png'),
    menuImg: require('../assets/icon/menu.png'),
    camImg: require('../assets/icon/cam.png'),
    memberImg: require('../assets/icon/member.png'),
    msgImg: require('../assets/icon/msg.png'),
    callImg: require('../assets/icon/call.png'),
    attendImg: require('../assets/icon/Attend.png'),
    attendYellowImg: require('../assets/icon/AttendYlw.png'),
    renewPackageImg: require('../assets/icon/renew_package.png'),
    user1Img: require('../assets/icon/user1.png'),
    deleteImg: require('../assets/icon/delete.png'),
    searchImg: require('../assets/icon/search.png'),
    filterImg: require('../assets/icon/filter.png'),
    sortByImg: require('../assets/icon/sort_by.png'),
    userYellowImg: require('../assets/icon/userYellow.png'),
    nonSelecteImg: require('../assets/icon/non_selecte.png'),
    nonSelecteImg: require('../assets/icon/non_selecte.png'),
    circleImg: require('../assets/icon/circle.png'),
    crossImg: require('../assets/icon/cross.png'),
    camImg: require('../assets/icon/cam.png'),
    calenderImg: require('../assets/icon/calender.png'),
    greenImg: require('../assets/icon/green.png'),
    redImg: require('../assets/icon/red.png'),
    addImg: require('../assets/icon/add.png'),
    dotImg: require('../assets/icon/dot.png'),
    backImg: require('../assets/icon/back.png'),
    userPaidImg: require('../assets/icon/user-paid.png'),
    leftImg: require('../assets/icon/left.png'),
    rightImg: require('../assets/icon/right.png'),
    whBgImg: require('../assets/icon/Wh-bg.png'),
    selelecteImg: require('../assets/icon/selelecte.png'),
    userImg: require('../assets/icon/user.png'),
    editImg: require('../assets/icon/edit.png'),
  };
export default  images;