const strings = {
  onboarding: {
    membership: {
      title: 'Title',
      amount: "Amount",
      details: 'Details',
      startDate: 'Start Date',
      endDate: 'End Date'
    },
    profile: {
      gymName: 'Gym Name',
      gymID: "Gym ID",
      gymAddress: 'Gym Address',
      firstName: 'First Name',
      lastName: 'Last Name',
      gender : 'Gender',
      password: 'Password',
      gymAddress: 'Gym Address',
      email: 'Email',
      phoneNo : 'Phone No.',
      dob: 'D.O.B',
      gymTimings: 'Gym Timings',
      gymDays: 'Gym Days',
    },
    gymInfo: {
      gymName: 'Gym Name',
      gymID: "Gym ID",
      gymTimings: 'Gym Timings',
      gymDays: 'Gym Days',
      gymAddress: 'Gym Address',
      gymOwnerName: 'Gym Owner Name',
      gymOwnerPhoneNo: 'Gym Owner Phone No.',
      gymOwnerAddress: 'Gym Owner Address',
    },
    visitor: {
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email',
      address: 'Address',
      dateOfJoin: 'Date of join',
      dateOfVisit: 'Date of visit',
      numberOfVisit: 'No. of visit',
      gender : 'Gender',
      phoneNo : 'Phone Number',
    },
    trainer: {
      firstName: 'First Name',
      lastName: 'Last Name',
      idTrainer: 'ID',
      phoneNo : 'Phone No.',
      email: 'Email',
      password: 'Password',
      address: 'Address',
      gender : 'Gender',
      salary: 'Salary',
      uploadIDProof: 'Upload ID Proof',
      shiftDays: 'Shift days',
      shiftTimings: 'Shift timings',
      dob: 'D.O.B',
      dateOfJoin: 'Date of join',
      permissionToAccess: 'Permission to access',
      visitor: 'Visitor',
      member: 'Member',
      event: 'Event',
      trainerType: 'Type',
    },
    member: {
      firstName: 'First Name',
      lastName: 'Last Name',
      idMember: 'Member ID',
      dateOfJoin: 'Date of join',
      gender : 'Gender',
      password: 'Password',
      trainerType: 'Type',
      trainerName: 'Trainer Name',
      uploadIDProof: 'Upload ID Proof',
      email: 'Email',
      address: 'Address',
      phoneNo : 'Phone No.',
      dob: 'D.O.B',
      membershipPlan: 'Membership Plan',
      membershipDetail: 'Membership Detail',
      amount: 'Amount',
      startDate: 'Start Date',
      endDate: 'End Date',
      totalAmount: 'Total Amount',
      discount: 'Discount',
      paymentType: 'Payment Type',
      dueAmount: 'Due Amount',
    },
    memberDetail: {
      addNewMembership: 'Add new Membership',
      currentMembershipDetails: 'Current Membership details',
      purchase: 'Purchase',
      attendance: 'Attendance',
    },
    changePassword: {
      currentPassword: 'Current Password',
      newPassword: "New Password",
      confirmPassword: "Confirm Password",
    },
  },
  alert :{
    profileAlertTilte: 'Profile ',
    membershipAlertTilte: 'Membership ',
    eventAlertTilte: 'Event ',
    visitorAlertTilte: 'Visitor ',
    trainerAlertTilte: 'Trainer ',
    memberAlertTilte: 'Member ',
    attendanceAlertTilte: 'Attendance ',
    changePasswordAlertTilte: 'Change Password ',
    addDataAlert: 'has been added suceessfully',
    updateDateAlert: 'has been updated suceessfully',
    deleteDataAlert: 'has been deleted suceessfully',
    changePasswordAlert: 'Password has been changed suceessfully',
    checkedInAlert: 'checked in suceessfully',
    checkedOutAlert: 'checked out suceessfully',
  },
  noDataFound :
  {
    membershipTilte: 'Membership',
    eventTilte: 'Event',
    visitorTilte: 'Visitor',
    trainerTilte: 'Trainer',
    memberTilte: 'Member',
    purcahse: 'Purcahse',
    attendance: 'Attendance',
    no: 'No ',
    found: ' Found',
    startAdding : 'Start Adding ',
    clickBottomPlusIcon: ' Click Bottom + Icon',
    clickAddNewMembership: ' Click Add New Membership',
    noRecord: ' There is no record',
  }
}

export default strings